language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.0
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.6
  - 2.3.7
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - 2.5.0
  - 2.5.1
  - ruby-head
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - "gem update --system"
matrix:
  allow_failures:
    - rvm: ruby-head
script:
  - bundle exec rubocop
  - bundle exec rspec
notifications:
  email:
    - team@wpscan.org
